[package]
name = "organisator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version = "0.3.33", features = ["local-offset"] }
rocket = "0.5.0"

[features]
local-offset = []
